### ISSUE TITLE
WaitFor can't be awaited in TS

### ISSUE THREAD

**Issue by NaZaRKIN123** [jcoreio/chai-wait-for#2]
Hello,

I'm trying to use this plugin with TS but not sure what is missing. So bindWaitFor returns the chai assertion but not the promise. So I'm getting an error: "'await' has no effect on the type of this expression.ts(80007)" 
Also when it's not awaited it always pass, it doesn't matter what the inputs are.

Can you help to fix it?

My code example:
```
import { Then } from '@cucumber/cucumber'
import { use } from 'chai'
import chai_wait_for, { bindWaitFor } from 'chai-wait-for'

use(chai_wait_for)
const waitFor = bindWaitFor({
  timeout: 5000,
  retryInterval: 300,
})

Then(/test/, () => {
  const myObj = { foo: 0 }

  setInterval(() => myObj.foo++, 1000)

  // Then use it just like you would expect() (but note you must await it!)
  await waitFor(myObj).to.have.property('foo').that.equals(3)
})
```

**Comment by jedwards1211** [comment]
Yeah I'll have to spend some time investigating this, having `waitFor` return a `Chai.PromisedAssertion` (defined by `chai-as-promised`) works, but I need to figure out what to do if you aren't using `chai-as-promised` (because it adds language chains to the TS defs that won't be present at runtime if you aren't adding the `chai-as-promised` plugin)

**Comment by jedwards1211** [comment]
Cheers, let me know if you still have problems with the 2.0.3 release

**Comment by NaZaRKIN123** [comment]
Hello @jedwards1211 , the error is gone and no await is needed. Thanks! But it still always pass. I'll open another issue.
